#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

message="$(cat $1)"
pattern="^(portfolio|nearbai|whisquers|ui-kit|common|shared|chore|config): [a-z].*$"
if ! echo "$message" | grep -iqE "$pattern";
then
  echo "Invalid Commit Message Format"
  echo ""
  echo "Valid pattern:"
  echo "portfolio|nearbai|whisquers|ui-kit|common|shared|chore|config:<space><message starting with a lowercase letter>"
  echo ""
  echo "Example:"
  echo "feat: add textbox component"
  echo ""
  echo "Your commit message was:"
  echo $message
  echo ""
  echo "------------------------------"
  echo "For more information, check script in .husky/commit-msg"
  echo "-"
  exit 1
fi
